spring:
  application:
    name: taskflowapi
  datasource:
    url: "jdbc:postgresql://localhost:5432/taskflow_db"
    username: postgres
    password: 122485
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
